export default text = {
  main_title:"Welcome to Diabetes Diary",
  responsibility_title:"Your own responsibility",
  responsibility_content:"Diabetes Diary is an app developed to help people with diabetes to manage their disease better. Please keep in mind that you still have the responsibility for your own decisions about how to use the application, and how to manage your diabetes.",
  data_title:"Data storage",
  data_content:"Please note that Diabetes Diary stores the information you enter about your health and habits, information that you might want to keep private. It is possible to protect the information, for example by locking the device with a pattern or a code. Normally, the database with data entries is stored where it can be accessed only by Diabetes Diary. However, if you choose to use the feature for exporting or sending the database, other applications may also be able to read the database.",
  understand_title:"I’ve read and understood the text above, now show me the app!",
  endText:"The Norwegian Centre for E-health Research hopes you will find the app useful, and that it helps you with managing your diabetes.",
  pressOk:"Press OK to continue.",
  hi:"Hi!",
  welcome:"Welcome to the Diabetes Diary App! We would like to know a little about you. Are you a :",
  color:"First of all, do you have any problem reading this ? What color do you want to use",
  name:"It looks better now! How do you want to be called?",
  nice:"Nice to meet you ",
  type:"What type of diabetes do you have",
}
